#!/bin/bash

source ./common

MSG=https://raw.githubusercontent.com/brandondiamond/wesay/master/message
SPOKEN="/tmp/$$.wesay.log"

function get_msgs {
	curl "$MSG?$RANDOM" 2> /dev/null;
}

function do_msg {
	let -i ts=$1;
	let -i now=$(get_time);
	
	txt="${*:2}";
	echo ">>> $ts, $now, $txt"
	echo $(( $ts <= $now )) , $((($now - $ts) <= $TTL ))
	if (( $ts <= $now && ($now - $ts) <= $TTL )); then
		if cat $SPOKEN | grep -q "\b$ts\b"; then
			echo "SEEN: ts=$ts now=$now txt=$txt" >&2
		else
			echo $ts >> $SPOKEN
			echo "> SAY: ts=$ts now=$now txt=$txt" >&2
			say "$txt";
		fi
	else
		echo "OLD: ts=$ts now=$now txt=$txt" >&2
	fi
}

touch $SPOKEN

while true; do
	get_msgs | while read -r line; do
		do_msg $line
	done
	sleep 0.5
done
