#!/bin/bash

source ./common

MSG=https://raw.githubusercontent.com/brandondiamond/wesay/master/message
SPOKEN=""


get_msgs() {
	curl "$MSG?$RANDOM" 2> /dev/null;
}

do_msg() {
	let -i ts=$1;
	let -i now=$(get_time);
	
	txt="${*:2}";

	if (( $ts <= $now && ($now - $ts) <= $TTL )); then
		if echo "$SPOKEN" | grep -q "\b$ts\b"; then
			echo "SEEN: ts=$ts now=$now txt=$txt" >&2
		else
			SPOKEN="$SPOKEN $ts";
			echo "> SAY: ts=$ts now=$now txt=$txt" >&2
			say "$txt";
		fi
	else
		echo "OLD: ts=$ts now=$now txt=$txt" >&2
	fi
}

while true; do
	get_msgs | while read -r line; do
		do_msg $line
	done
	sleep 0.5
done
